export const routes = {
  home: '/',
  logout: '/wyloguj',
  login: '/logowanie',
  register: '/rejestracja',
  calendar: '/kalendarz',
  clients: '/klienci',
  client: '/klienci/:id',
  newClient: '/klienci/nowy',
  products: '/produkty',
  product: '/produkty/:id',
  newProduct: '/produkty/nowy',
  settings: '/ustawienia',
  rents: '/wypozyczenia',
  rent: '/wypozyczenia/:id',
  newRent: '/wypozyczenia/nowy',
  finances: '/historia',
  updatePassword: '/ustawienia/zmiana-hasla',
};
